---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Evin.
--- DateTime: 2024/11/29 15:49
---
-- 优惠券id
local voucherId = ARGV[1]
-- 用户id
local userId = ARGV[2]

-- 优惠券库存Key
local stockKey = 'seckill:stock:' .. voucherId
-- 优惠券下单用户Key
local orderKey = 'seckill:order:' .. voucherId

-- 判断优惠券库存是否充足
if(tonumber(redis.call('GET', stockKey)) < 1)
    then return 1
end

-- 判断是否满足一人一单
if(redis.call('sismember', orderKey, userId) == 1)
    then return 2;
end
-- 扣减库存
redis.call('incrby', stockKey, -1)
-- 保存下单用户
redis.call('sadd', orderKey, userId)

return 0