---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Evin.
--- DateTime: 2024/11/28 9:29
---

if(redis.call('get', KEYS[1]) == ARGV[1]) then
    return redis.call('del', KEYS[1])
end
return 0
